-- ==========================================
-- 0. Multi-tenant Core (テナント管理基盤)
-- ==========================================

-- テナント（会社・組織）
create table tenants (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  created_at timestamptz default now()
);

-- ユーザー所属管理 (Supabase Auth との紐付け)
-- ※ RLSポリシーで「自分の所属するテナントのデータだけ」を見れるようにするために使用
create table organization_members (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  tenant_id uuid references tenants(id) on delete cascade not null,
  role text default 'member', -- admin, member, read_only 等
  created_at timestamptz default now(),
  unique(user_id, tenant_id)
);

-- ==========================================
-- 1. Master Data (マスタデータ)
-- ==========================================

-- 1. Equipment Groups
create table equipment_groups (
  id bigint generated by default as identity (start with 1) primary key,
  tenant_id uuid references tenants(id) not null, -- ★追加
  name text not null
);

-- 2. Equipments
create table equipments (
  id bigint generated by default as identity (start with 101) primary key,
  tenant_id uuid references tenants(id) not null, -- ★追加
  name text not null
);

-- 3. Equipment Group Members
create table equipment_group_members (
  id bigint generated by default as identity (start with 1001) primary key,
  tenant_id uuid references tenants(id) not null, -- ★追加
  equipment_group_id bigint references equipment_groups(id) on delete cascade,
  equipment_id bigint references equipments(id) on delete cascade,
  -- 同じペアが重複しないように制約 (テナント単位である必要はないが念のため)
  unique(equipment_group_id, equipment_id)
);

-- 4. Products
create table products (
  id bigint generated by default as identity (start with 10001) primary key,
  tenant_id uuid references tenants(id) not null, -- ★追加
  name text not null,
  code text, 
  type text,
  -- ★変更: テナント内で品番(code)がユニークであればOK（他社との重複は許容）
  unique(tenant_id, code) 
);

-- 5. Process Routings
create table process_routings (
  id bigint generated by default as identity (start with 100001) primary key,
  tenant_id uuid references tenants(id) not null, -- ★追加
  product_id bigint references products(id) on delete cascade,
  sequence_order int not null,
  process_name text,
  equipment_group_id bigint references equipment_groups(id),
  setup_time_seconds int default 0,
  unit_time_seconds numeric(10, 4) not null
);

-- ==========================================
-- 2. Transaction Data (業務データ)
-- ==========================================

-- 6. Orders
create table orders (
  id bigint generated by default as identity (start with 1000001) primary key,
  tenant_id uuid references tenants(id) not null, -- ★追加
  order_number text,
  product_id bigint references products(id),
  quantity int not null,
  order_date timestamptz default now(),
  deadline_date date,
  is_scheduled boolean default false,
  -- ★変更: テナント内で注文番号がユニーク
  unique(tenant_id, order_number)
);

-- 7. Production Schedules
create table production_schedules (
  id bigint generated by default as identity (start with 10000001) primary key,
  tenant_id uuid references tenants(id) not null, -- ★追加
  order_id bigint references orders(id) on delete cascade,
  process_routing_id bigint references process_routings(id),
  equipment_id bigint references equipments(id),
  start_datetime timestamptz not null,
  end_datetime timestamptz not null
);

-- インデックス (テナントIDを含めた複合インデックスにすると検索がより高速になります)
create index idx_schedules_tenant_equip_end on production_schedules (tenant_id, equipment_id, end_datetime desc);
create index idx_schedules_tenant_order on production_schedules (tenant_id, order_id);
